language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v tests.test_message
  - python -m unittest -v tests.test_analysis