name: Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
      
      - name: setup
        run: python setup.py install
      
      - name: test message
        run: python tests/test_message.py
      
      - name: test analysis
        run: python tests/test_analysis.py
